import assert from "node:assert/strict";
import { test } from "node:test";
import * as path from "node:path";
import { parse } from "node-html-parser";
import { rollup } from "rollup";
import type {
  InputPluginOption,
  OutputAsset,
  OutputChunk,
  RollupOutput,
} from "rollup";

import html2 from "../dist/index.js";

type BundleOutput = RollupOutput["output"][number];

const fixturesDir = path.join(import.meta.dirname, "fixtures");

function virtualModules(modules: Record<string, string>): InputPluginOption {
  return {
    name: "test-virtual-modules",
    resolveId(id) {
      return id in modules ? id : null;
    },
    load(id) {
      return modules[id] ?? null;
    },
  };
}

function getAsset(
  output: BundleOutput[],
  fileName: string,
): Extract<BundleOutput, OutputAsset> {
  const asset = output.find(
    (item): item is Extract<BundleOutput, OutputAsset> =>
      item.type === "asset" && item.fileName === fileName,
  );
  assert.ok(asset, `Expected asset ${fileName} to be emitted`);
  return asset;
}

function getChunk(
  output: BundleOutput[],
  name: string,
): Extract<BundleOutput, OutputChunk> {
  const chunk = output.find(
    (item): item is Extract<BundleOutput, OutputChunk> =>
      item.type === "chunk" && item.name === name,
  );
  assert.ok(chunk, `Expected chunk ${name} to be emitted`);
  return chunk;
}

type GenerateOptions = {
  format?: "es" | "iife";
  html2Options: Parameters<typeof html2>[0];
  input?: Record<string, string> | string;
  modules?: Record<string, string>;
  outputOptions?: Parameters<Awaited<ReturnType<typeof rollup>>["generate"]>[0];
  plugins?: InputPluginOption[];
};

async function generate({
  format = "es",
  html2Options,
  input = {
    main: "main.js",
    legacy: "legacy.js",
    ignored: "ignored.js",
  },
  modules = {
    "main.js": 'console.log("main");',
    "legacy.js": 'console.log("legacy");',
    "ignored.js": 'console.log("ignored");',
  },
  outputOptions = {},
  plugins = [],
}: GenerateOptions): Promise<BundleOutput[]> {
  const bundle = await rollup({
    input,
    plugins: [virtualModules(modules), ...plugins, html2(html2Options)],
  });

  try {
    return (
      await bundle.generate({
        format,
        ...outputOptions,
      })
    ).output;
  } finally {
    await bundle.close();
  }
}

async function rollupWithHtml2(
  options: Parameters<typeof html2>[0],
  format: "es" | "iife" = "es",
): Promise<BundleOutput[]> {
  return generate({
    format,
    html2Options: options,
  });
}

async function assertBuildRejects(
  options: Parameters<typeof html2>[0],
  expected: RegExp,
  format: "es" | "iife" = "es",
  input?: Record<string, string> | string,
): Promise<void> {
  const generateOptions: GenerateOptions = {
    format,
    html2Options: options,
  };
  if (input !== undefined) {
    generateOptions.input = input;
  }
  await assert.rejects(generate(generateOptions), expected);
}

test("generates an HTML asset with configured entries and externals", async () => {
  const output = await rollupWithHtml2({
    fileName: "index.html",
    template: "<html><head><title>Old title</title></head><body></body></html>",
    title: "HTML2 test",
    meta: {
      description: "Generated by a test",
    },
    onlinePath: "/static/assets",
    entries: {
      main: { tag: "script", type: "module" },
      legacy: { tag: "script", nomodule: true },
    },
    externals: {
      before: [
        { tag: "link", href: "https://cdn.example/reset.css" },
        { tag: "script", text: "window.before = true;" },
      ],
      after: [{ tag: "style", text: "body { color: black; }" }],
    },
  });

  const mainChunk = getChunk(output, "main");
  const legacyChunk = getChunk(output, "legacy");
  const html = String(getAsset(output, "index.html").source);
  const document = parse(html);

  assert.equal(document.querySelector("title")?.textContent, "HTML2 test");
  assert.equal(
    document.querySelector('meta[name="description"]')?.getAttribute("content"),
    "Generated by a test",
  );
  assert.equal(
    document
      .querySelector('link[href="https://cdn.example/reset.css"]')
      ?.getAttribute("rel"),
    "stylesheet",
  );
  assert.equal(
    document.querySelector("script")?.textContent,
    "window.before = true;",
  );
  assert.equal(
    document.querySelector("style")?.textContent,
    "body { color: black; }",
  );
  assert.ok(
    document.querySelector(
      `script[type="module"][src="/static/assets/${mainChunk.fileName}"]`,
    ),
  );
  assert.ok(
    document.querySelector(
      `script[nomodule][src="/static/assets/${legacyChunk.fileName}"]`,
    ),
  );
});

test("adds the configured title when the template has no title element", async () => {
  const output = await rollupWithHtml2({
    fileName: "index.html",
    template: "<html><head></head><body></body></html>",
    title: "HTML2 test",
  });

  const html = String(getAsset(output, "index.html").source);
  const document = parse(html);

  assert.equal(document.querySelector("title")?.textContent, "HTML2 test");
});

test("does not inject excluded entry chunks", async () => {
  const output = await rollupWithHtml2({
    fileName: "index.html",
    template: "<html><head></head><body></body></html>",
    exclude: ["ignored"],
  });

  const ignoredChunk = getChunk(output, "ignored");
  const html = String(getAsset(output, "index.html").source);

  assert.doesNotMatch(html, new RegExp(ignoredChunk.fileName));
});

test("reads an HTML template file and derives the emitted file name", async () => {
  const output = await generate({
    html2Options: {
      template: path.join(fixturesDir, "template.html"),
    },
    outputOptions: {
      dir: "dist-test",
    },
  });

  const html = String(getAsset(output, "template.html").source);
  const document = parse(html);

  assert.equal(document.querySelector("html")?.getAttribute("lang"), "en");
  assert.ok(document.querySelector('script[src="/main.js"]'));
});

test("emits configured HTML file names in subdirectories", async () => {
  const output = await rollupWithHtml2({
    fileName: "nested/index.html",
    template: "<html><head></head><body></body></html>",
  });

  const html = String(getAsset(output, "nested/index.html").source);
  const document = parse(html);

  assert.ok(document.querySelector('script[src="/main.js"]'));
});

test("rejects HTML file names outside the output directory", async () => {
  await assertBuildRejects(
    {
      fileName: "../index.html",
      template: "<html><head></head><body></body></html>",
    },
    /neither absolute nor relative paths/,
  );
});

test("can disable generated file injection", async () => {
  const output = await rollupWithHtml2({
    fileName: "index.html",
    inject: false,
    template: "<html><head></head><body></body></html>",
  });

  const html = String(getAsset(output, "index.html").source);

  assert.doesNotMatch(html, /<script/);
  assert.doesNotMatch(html, /<link/);
});

test("can inject script tags into the head", async () => {
  const output = await rollupWithHtml2({
    entries: {
      main: { tag: "script" },
    },
    externals: {
      before: [{ tag: "script", src: "https://cdn.example/library.js" }],
    },
    fileName: "index.html",
    inject: "head",
    template: "<html><head></head><body></body></html>",
  });

  const mainChunk = getChunk(output, "main");
  const html = String(getAsset(output, "index.html").source);
  const document = parse(html);

  assert.ok(
    document.querySelector('head script[src="https://cdn.example/library.js"]'),
  );
  assert.ok(
    document.querySelector(`head script[src="/${mainChunk.fileName}"]`),
  );
  assert.equal(document.querySelectorAll("body script").length, 0);
});

test("injects bundled CSS assets as stylesheet links", async () => {
  const output = await generate({
    html2Options: {
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    },
    plugins: [
      {
        name: "test-css-asset",
        generateBundle() {
          this.emitFile({
            fileName: "bundle.css",
            source: "body { color: black; }",
            type: "asset",
          });
        },
      },
    ],
  });

  const html = String(getAsset(output, "index.html").source);
  const document = parse(html);

  assert.ok(
    document.querySelector('head link[rel="stylesheet"][href="/bundle.css"]'),
  );
});

test("replaces existing meta and favicon links and emits the favicon asset", async () => {
  const output = await rollupWithHtml2({
    favicon: path.join(fixturesDir, "favicon.ico"),
    fileName: "index.html",
    meta: {
      description: "New description",
    },
    onlinePath: "assets/",
    template:
      '<html><head><meta name="description" content="Old"><link rel="shortcut icon" href="old.ico"></head><body></body></html>',
  });

  const html = String(getAsset(output, "index.html").source);
  const document = parse(html);

  assert.equal(
    document.querySelector('meta[name="description"]')?.getAttribute("content"),
    "New description",
  );
  assert.equal(
    document.querySelector('link[rel="shortcut icon"]')?.getAttribute("href"),
    "assets/favicon.ico",
  );
  assert.equal(getAsset(output, "favicon.ico").source.toString(), "icon\n");
});

test("injects favicons plugin output and minifies generated HTML", async () => {
  const output = await generate({
    html2Options: {
      fileName: "index.html",
      minify: {
        collapseWhitespace: true,
      },
      template: "<html><head></head><body></body></html>",
    },
    plugins: [
      {
        name: "test-favicons-output",
        generateBundle(options) {
          Object.assign(options, {
            __favicons_output: [
              '<link rel="apple-touch-icon" href="icon.png">',
            ],
          });
        },
      },
    ],
  });

  const html = String(getAsset(output, "index.html").source);
  const document = parse(html);

  assert.ok(
    document.querySelector('link[rel="apple-touch-icon"][href="icon.png"]'),
  );
  assert.doesNotMatch(html, /\n\s+/);
});

test("warns about unknown options, string inject values, and excluded configured entries", async () => {
  const warnings: string[] = [];
  const bundle = await rollup({
    input: "main.js",
    onwarn(warning) {
      warnings.push(warning.message);
    },
    plugins: [
      virtualModules({ "main.js": 'console.log("main");' }),
      html2({
        entries: {
          main: { tag: "script" },
        },
        exclude: ["main"],
        fileName: "index.html",
        inject: "invalid",
        template: "<html><head></head><body></body></html>",
        unknown: true,
      } as unknown as Parameters<typeof html2>[0]),
    ],
  });

  try {
    await bundle.generate({ format: "es" });
  } finally {
    await bundle.close();
  }

  assert.deepEqual(warnings, [
    "[plugin html2] Ignoring unknown option `unknown`",
    '[plugin html2] Invalid `inject` must be `true | false | "head" | "body" | undefined`',
    '[plugin html2] Excluding a configured entry "main"',
  ]);
});

test("validates unsupported option shapes during buildStart", async () => {
  await assertBuildRejects(
    {
      fileName: "index.html",
      preload: true,
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /The `preload` option is deprecated/,
  );

  await assertBuildRejects(
    {
      externals: [],
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /`externals` must be an object/,
  );

  await assertBuildRejects(
    {
      favicon: path.join(fixturesDir, "missing.ico"),
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    },
    /The provided favicon file does't exist/,
  );
});

test("validates entry and external tag options during buildStart", async () => {
  await assertBuildRejects(
    {
      entries: {
        main: { tag: "style" },
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /An entry cannot have a `tag` property set to "style"/,
  );

  await assertBuildRejects(
    {
      entries: {
        main: { tag: "iframe" },
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /Invalid value for the `tag` option/,
  );

  await assertBuildRejects(
    {
      entries: {
        main: { tag: "script", nomodule: "yes" },
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /Invalid value for the `nomodule` option/,
  );
});

test("validates module-only entries against output format", async () => {
  await assertBuildRejects(
    {
      entries: {
        main: { tag: "script", nomodule: true, type: "module" },
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    },
    /nomodule` option enabled and `type` set to "module"/,
  );

  await assertBuildRejects(
    {
      entries: {
        main: { tag: "script", type: "module" },
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    },
    /output\.format.*"iife"/,
    "iife",
    "main.js",
  );
});

test("validates generated HTML and external resource options", async () => {
  await assertBuildRejects(
    {
      fileName: "index.html",
      template: "<body></body>",
    },
    /does not contain the `html` tag/,
  );

  await assertBuildRejects(
    {
      externals: {
        before: [{ href: "https://cdn.example/app.js" }],
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /`tag` property must be defined explicitly for `externals`/,
  );

  await assertBuildRejects(
    {
      externals: {
        before: [{ tag: "link", rel: "preload" }],
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /rel` option.*preload.*no `as` option/s,
  );

  await assertBuildRejects(
    {
      externals: {
        before: [{ tag: "script" }],
      },
      fileName: "index.html",
      template: "<html><head></head><body></body></html>",
    } as unknown as Parameters<typeof html2>[0],
    /One of `src`, `href`, or `text` property must be defined/,
  );
});

test("requires fileName when template is an HTML string", async () => {
  await assert.rejects(
    rollup({
      input: "main.js",
      plugins: [
        virtualModules({ "main.js": 'console.log("main");' }),
        html2({
          template: "<html><head></head><body></body></html>",
        }),
      ],
    }),
    /When `template` is an HTML string the `fileName` option must be defined/,
  );
});
